### ISSUE TITLE
Supplied `Makefile' does not have 'install' capability, and CMakeFile.txt breaks build

### ISSUE THREAD

**Issue by i336** [MatzeB/libfirm#3]
In my efforts to try and build fluffy (which [haven't been going too well](https://github.com/MatzeB/fluffy/issues/2)), I attempted to throw `sudo make install` at libfirm's `Makefile`, and was greeted with

    make: *** No rule to make target `install'.  Stop.

Huh.

Looking around and wondering what to do next, I noticed `CMakeLists.txt`. Aha!

Or not:

    $ cmake .
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/i336/libfirm
    $ make
    [  1%] Generating gen/ir/be/TEMPLATE/gen_TEMPLATE_new_nodes.c.inl
    Fatal error: Could not open /home/i336/libfirm/gen/ir/be/TEMPLATE/gen_TEMPLATE_new_nodes.c.inl, reason: No such file or directory
    make[2]: *** [gen/ir/be/TEMPLATE/gen_TEMPLATE_new_nodes.c.inl] Error 2
    make[1]: *** [CMakeFiles/firm.dir/all] Error 2
    make: *** [all] Error 2

Apparently the `cmake` build-file generates a broken `Makefile`. I had a look at it, but I don't understand the structure of the project, so the necessary changes are beyond me (it seems to me that the project's directory structure changed at somepoint, and `CMakeLists.txt` wasn't updated).

I don't consider this a blocking or breaking issue, because it's not affecting `libfirm`'s functionality; I only discovered this while trying to build fluffy (which currently isn't working in any case). That said, I'd remove `CMakeLists.txt`, if just for the time being, and *possibly* add an `install` target to the `Makefile` :P

PS. This is an awesome project. FYI, `cparser` built fine and appears to chomp `.c` files happily - why on earth doesn't everyone know about this 3.7MB C++ compiler?! \^\^

**Comment by MatzeB** [comment]
This is fixed now.
(but is not enough to get fluffy running again).

**Comment by i336** [comment]
Oh, cool! :D

(Fluffy is stull #mildlyinteresting to me - maybe the [relevant ticket I opened](https://github.com/MatzeB/fluffy/issues/2) would be the right place to explain why?)
